import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime


def _build_html(summaries: list[dict]) -> str:
    now = datetime.now()
    today = f"{now.strftime('%B')} {now.day}, {now.year}"
    sections = []

    for s in summaries:
        points_html = ""
        for kp in s.get("key_points", []):
            ts = f'<span style="color:#888;font-size:0.85em">[{kp["timestamp"]}]</span> ' if kp.get("timestamp") else ""
            points_html += f"<li>{ts}{kp['point']}</li>\n"

        sections.append(f"""
<div style="margin-bottom:32px;border-bottom:1px solid #eee;padding-bottom:24px">
  <div style="font-size:0.8em;color:#888;text-transform:uppercase;letter-spacing:0.05em">{s['channel_name']}</div>
  <h2 style="margin:4px 0 8px;font-size:1.1em">
    <a href="{s['url']}" style="color:#1a0dab;text-decoration:none">{s['title']}</a>
  </h2>
  <p style="margin:0 0 12px;color:#333;font-style:italic">{s['headline']}</p>
  <ul style="margin:0;padding-left:20px;color:#333;line-height:1.6">
    {points_html}
  </ul>
</div>""")

    body = "\n".join(sections)
    return f"""<!DOCTYPE html>
<html>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:640px;margin:0 auto;padding:24px;color:#222">
  <h1 style="font-size:1.3em;border-bottom:2px solid #222;padding-bottom:8px;margin-bottom:24px">
    Video Digest &mdash; {today}
  </h1>
  {body}
  <p style="font-size:0.75em;color:#aaa;margin-top:32px">Generated by video-summarizer</p>
</body>
</html>"""


def send_digest(summaries: list[dict], config: dict, smtp_password: str) -> None:
    email_cfg = config["email"]
    from_addr = email_cfg["from"]
    to_addr = email_cfg["to"]
    prefix = email_cfg.get("subject_prefix", "[VideoDigest]")
    count = len(summaries)
    now = datetime.now()
    today = f"{now.strftime('%b')} {now.day}"  # e.g. "Apr 5"
    subject = f"{prefix} {count} new video{'s' if count != 1 else ''} \u2014 {today}"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = from_addr
    msg["To"] = to_addr
    msg.attach(MIMEText(_build_html(summaries), "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(from_addr, smtp_password.replace("-", ""))
        server.sendmail(from_addr, to_addr, msg.as_string())
